/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as RelogiosAntigosRouteImport } from './routes/relogios-antigos'
import { Route as RestauracoesRouteImport } from './routes/restauracoes'
import { Route as RelogiosIdRouteImport } from './routes/relogios/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const RelogiosAntigosRoute = RelogiosAntigosRouteImport.update({
  id: '/relogios-antigos',
  path: '/relogios-antigos',
  getParentRoute: () => rootRouteImport,
} as any)
const RestauracoesRoute = RestauracoesRouteImport.update({
  id: '/restauracoes',
  path: '/restauracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelogiosIdRoute = RelogiosIdRouteImport.update({
  id: '/relogios/$id',
  path: '/relogios/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRoute
  '/relogios-antigos': typeof RelogiosAntigosRoute
  '/restauracoes': typeof RestauracoesRoute
  '/relogios/$id': typeof RelogiosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRoute
  '/relogios-antigos': typeof RelogiosAntigosRoute
  '/restauracoes': typeof RestauracoesRoute
  '/relogios/$id': typeof RelogiosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRoute
  '/relogios-antigos': typeof RelogiosAntigosRoute
  '/restauracoes': typeof RestauracoesRoute
  '/relogios/$id': typeof RelogiosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/relogios-antigos'
    | '/restauracoes'
    | '/relogios/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/relogios-antigos'
    | '/restauracoes'
    | '/relogios/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/relogios-antigos'
    | '/restauracoes'
    | '/relogios/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogoRoute: typeof CatalogoRoute
  RelogiosAntigosRoute: typeof RelogiosAntigosRoute
  RestauracoesRoute: typeof RestauracoesRoute
  RelogiosIdRoute: typeof RelogiosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relogios-antigos': {
      id: '/relogios-antigos'
      path: '/relogios-antigos'
      fullPath: '/relogios-antigos'
      preLoaderRoute: typeof RelogiosAntigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restauracoes': {
      id: '/restauracoes'
      path: '/restauracoes'
      fullPath: '/restauracoes'
      preLoaderRoute: typeof RestauracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relogios/$id': {
      id: '/relogios/$id'
      path: '/relogios/$id'
      fullPath: '/relogios/$id'
      preLoaderRoute: typeof RelogiosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogoRoute: CatalogoRoute,
  RelogiosAntigosRoute: RelogiosAntigosRoute,
  RestauracoesRoute: RestauracoesRoute,
  RelogiosIdRoute: RelogiosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
